import angular from 'angular';

import 'angular-ui-router';

// Import our templates file (generated by Gulp)
// import './config/app.templates';

// Create and bootstrap application
const requires = [
    'ui.router'
];

// Mount on window for testing
window.app = angular.module('app', requires);

import constants  from './app.constants';
angular.module('app').constant('AppConstants', constants);

import appRoutes  from './app.routes';
angular.module('app').config(appRoutes);

import appConfig  from './app.config';
angular.module('app').config(appConfig);

angular.bootstrap(document, ['app'], {
    strictDi: true
});
